### ISSUE TITLE
Allow custom annotations on generated class files

### ISSUE THREAD

**Issue by Serranya** [fizzed/rocker#116]
I am using [jacoco](https://www.eclemma.org/jacoco/) to measure the test coverage in my projects.

Jacoco excludes classes from analysis that have a `@Generated` annotation with a retention of at least `CLASS`. The package of the annotation does not matter. Just the name and the retention.

I suggest that we add the possibility to annotate classes generated by rocker like this.

I see the following three options:

**Rocker provides its own annotation**
Create an `@com.fizzed.rocker.Generated` annotation and add that to all generated classes.
The user already has to include a rocker runtime dependency. Alternatively rocker could emit the source for the annotation as part of it's source generation.

**Rocker uses an established annotation**
Rocker could provide support for some established `@Generated` annotations. AFAIK there are none. Rocker could also try some fancy classpath scanning and search for `@Generated` annotations.

**Rocker provides a facillity to let the user provide its own Annotation(s)**
Rocker could provide the user with an option to let them specify (a list) of annotations to add. This way each project could provide its own `@Generated` annotation or reuse a third party `@Generated` annotation if they so desire.

@jjlauer and others,
what do you think? I would be willing to work on a PR. Which option do you prefer?

Edit:
I tried to add my own `@Generated` annotation via post-processing. Sadly the template model does not seem to expose the possibility to add annotations.

**Comment by Serranya** [comment]
I just noticed that I did not write which solution I prefer.

I would be in favor Solution 1 (Rocker provides its own annotation) where Rocker provides the annotation in its runtime.

**Comment by bendem** [comment]
The `@javax.annotation.Generated` option [was added a while ago](https://github.com/fizzed/rocker/issues/59) and [subsequently removed because it is part of a broken jigsaw module](https://github.com/fizzed/rocker/pull/82). If you wanted to add it back (not using the javax annotation but a custom rocker one), you would add it here:

https://github.com/fizzed/rocker/blob/28510d469a563f92daba3bfb7908c94c6bd5a143/rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java#L203

I'm sure a PR would be accepted if you opened it.

**Comment by jjlauer** [comment]
A rocker provided custom Generated annotation sounds like a great
solution.  Add the annotation to the runtime module and have the generator
add it.  I'm not sure there's any downside to adding it by default -- if
there was then a config option to disable including it would be useful.

**Comment by Serranya** [comment]
@bendem `@javax.annotation.Generated` is not what I am looking for. The annotation needs at least a retention of `CLASS` so that jacoco can pick it up.

@jjlauer great. I will prepare a PR. I agree about making the annotation optional.
