### ISSUE TITLE
Propose to support negation after @ ?

### ISSUE THREAD

**Issue by albert-kam** [fizzed/rocker#129]
Hi again ..

I have used a statically imported method called isReadonly, and using ```@isReadonly()``` works great. 

But when i need to negate it using ```@!isReadonly()```, this failed. I also tried ```@(!isReadonly())``` in vain. 

For now i ended up creating a new method just for this ```@isNotReadonly()```, which is also good, but it would be great if we can support negation ```!``` right after @ ?

**Comment by bendem** [comment]
The documentation states that `@(!isReadonly())` should work, if it doesn't, it's probably a bug. Can you maybe provide the generated java class for that template so we can see what's going on?

**Comment by albert-kam** [comment]
Yes ```@(!isReadonly())``` worked perfectly ! It could be it didnt recompile the modified template or maybe i was mistaken.  Sorry for the commotion.
