### ISSUE TITLE
rocker fails to compile if javascript "else" statements present

### ISSUE THREAD

**Issue by jshinobi** [fizzed/rocker#13]
this code failed to parse with error:
```javascript
<script>
    var time = 12;
    if (time < 10) {
        greeting = "Good morning";
    } else if (time < 20) {
        greeting = "Good day";
    } else {
        greeting = "Good evening";
    }
</script>
``` 
Parsing failed for 
...github/rocker/java6test/src/test/java/rocker/IfElseBlockMixedJavascript.rocker.html:[9,4] rocker/IfElseBlockMixedJavascript.rocker.html:[9,4] extraneous input '} else {' expecting {'{', '}', COMMENT, PLAIN, '@'}

Unfortunatly antlr4 project too complicated for me to fix issue.

**Comment by jjlauer** [comment]
@jshinobi Taking a look.  In the meantime, you can bypass the issue by escaping the { or } with `@{` or `@}`

**Comment by jjlauer** [comment]
@jshinobi I just committed a fix for the issue you discovered.  Tweaked your test just a bit and verified it works.  Before I publish to maven central can you give the master branch a try on your project(s) to as well?

**Comment by jshinobi** [comment]
It works.
Dear @jjlauer I am really grateful to you for this fix. Thank you.
