### ISSUE TITLE
Propose to support brackets to isolate java code ?

### ISSUE THREAD

**Issue by albert-kam** [fizzed/rocker#130]
So i wanted to generate ```${something-dynamic}.name```.

Doing it with ```@myVar.name``` doesnt work for this case.
So i tried ```@(myVar).name``` in hope to isolate ```myVar``` and let ```.name``` to be static text, but also failed.

For now i have to use ```@with (String varName = myVar + '.name')``` and use ```@varName``` instead.

**Comment by bendem** [comment]
According to https://github.com/fizzed/rocker/blob/master/docs/SYNTAX.md#eval-expression- `@(myVar + ".name")` should work.

**Comment by albert-kam** [comment]
Yes ```@(myVar).name``` worked perfectly after i retried ! It could be it didnt recompile the modified template or maybe i was mistaken.  Sorry for the commotion.
