### ISSUE TITLE
support Java 11

### ISSUE THREAD

**Issue by coffeecoder** [fizzed/rocker#153]
In Java 11 compilation is failing with the exception 
 Task :generateRockerTemplateSource FAILED FAILURE: Build failed with an exception.
What went wrong: Execution failed for task ':generateRockerTemplateSource'.
Unsupported javaVersion [11.]
not able to compile rocker template code using java11

**Comment by bendem** [comment]
Support for java 11 has been added in 2018 (#91). Which version are you using?
