### ISSUE TITLE
Unable to get hot-reload working with tomcat server

### ISSUE THREAD

**Issue by ghost** [fizzed/rocker#156]
Hi,

I'm unable to get hot-reload working in my application, I'm using tomcat (embedded) as server.

When compile is called during runtime, TemplateCompiler is unable to fetch classpathUrls from TomcatEmbeddedWebappClassLoader and hence get compilation errors.

![Capture](https://user-images.githubusercontent.com/58737407/129721177-2f8918bc-d6ca-489e-b5a7-7f1d9f979571.JPG)

Can classpath be appended with whatever System.getProperty("java.class.path") returns, if classpathUrls is empty ?

**Comment by JimmyWe11s** [comment]
https://stackoverflow.com/a/31785767
This could be a possible solution for the same

**Comment by jjlauer** [comment]
The hot reload support does rely quite a bit on classpaths existing as well as Rocker knowing where the class files live on disk, etc. I'm not really sure how your setup locally with Tomcat works or how you have embedded Rocker itself to give you much guidance.

**Comment by JimmyWe11s** [comment]
I have a spring boot web application which uses embedded tomcat as server with default configuration.
To get an idea of how rocker is used in the app you can have a look at this sample app [https://github.com/JimmyWe11s/demo](https://github.com/JimmyWe11s/demo)

Also, I took the opportunity of testing rocker with above solution, which uses classgraph's method of getting classpaths.
Built a rocker's snapshot out of that, tested with the application, and it worked. I also request you to test it.
Here is a snippet that I used. (Used version 4.8.115 of [classgraph](https://github.com/classgraph/classgraph))

![image](https://user-images.githubusercontent.com/58737407/130019002-204e8186-bb19-40a2-b6b2-1925c478ccc2.png)
