### ISSUE TITLE
Generation crashes with NPE if a non-normal file is present in the template directory

### ISSUE THREAD

**Issue by lenaschimmel** [fizzed/rocker#159]
The method [RockerUtil.listFileTree](https://github.com/fizzed/rocker/blob/4a8d6f11eaf2fb573ba3c142fe4b1464823f24fa/rocker-compiler/src/main/java/com/fizzed/rocker/compiler/RockerUtil.java#L160) throws a `NullPointerException` if there is any file within the template directory which is neither a "normal file" (as defined by [`File.isFile()`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#isFile())) nor a directory.

In my special case, I had a broken symlink in there, but I think other special files might also trigger this. Fixes which I can think of:
1. check with `else if (entry.isDirectory())`, so that special files are ignored and only actual directories are passed to the recursive method call
2. surround the for-loop with try-catch and print the path of the offending file, so that the user can delete / fix the file

**Comment by jjlauer** [comment]
Number 1 sounds like a good, simple fix. If you were interested in helping with the fix and submitted a PR, that would be awesome!
