### ISSUE TITLE
Spaces in empty @args list

### ISSUE THREAD

**Issue by jfendler** [fizzed/rocker#17]
Rocker is rather picky about any spaces in an empty list of arguments.

This all works:
```
@args()
@args ()
@args ( String myString )
```

but this doesn't:
```
@args( )
```
and fails with the rather "unintuitive" error message "Invalid java variable: name part never found".

**Comment by jjlauer** [comment]
Nice catch.  That error message should have had the line number at least, but I agree `@args ( )` should be acceptable.  It'd be awesome if you wanted to take a stab at fixing it -- I believe you'd only need to dive into the Argument parsing code which is fairly simple.  If not then I marked as an enhancement for a placeholder down the road (no guarantees on timing).

**Comment by jfendler** [comment]
PR is online. Unfortunately the first attempt resulted in Eclipse messing up the original import statements quite a bit, so I did another clean one.
Please test if this fixes the issue - I can't seem to get the Rocker packages build from git easily.
