### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by antoniopi** [fizzed/rocker#171]
It seems that the master branch has the support for Java17. Unfortunately there is no new version released on the maven central for it.
Is there any plan to release a new version anytime soon?
Thanks.

**Comment by jjlauer** [comment]
Oversight on my part not releasing Java 17 support.  I'll try to carve out some time to do that today/tomorrow and give 21 a try as well.

**Comment by jjlauer** [comment]
Version 1.4.0 was just shipped and released to maven central.  Should be available in a few hours.
