### ISSUE TITLE
Why rocker dont import List class?

### ISSUE THREAD

**Issue by mani1232** [fizzed/rocker#172]
![image](https://github.com/fizzed/rocker/assets/70480001/56b28151-69b0-47d8-91ec-fd030d598cb8)
![image](https://github.com/fizzed/rocker/assets/70480001/155affee-74f1-486c-9fb0-36003a47386c)

**Comment by mani1232** [comment]
Imports:

![image](https://github.com/fizzed/rocker/assets/70480001/ef604b4f-69a1-4add-9ab5-e65a7cabd4a0)

**Comment by jjlauer** [comment]
To be as useful to a wide variety of use cases, just like standard Java classes don't import List by default, we don't either.  You simply need to import java.util.List at the top of your rocker file and it'll work.
