### ISSUE TITLE
Change the semantics of the @ operator, to reduce nullpointerexceptions

### ISSUE THREAD

**Issue by awildturtok** [fizzed/rocker#25]
I would prefer it, if null values would not cause NullPointerExceptions, as it makes data modelling rather annoying. My setup sometimes contains empty values, and I find the proposed way of @Optional.ofNullable rather cumbersome and redundant. My current [workaround is a method toString inside my own default RockerTemplate](https://gist.github.com/awildturtok/0272344c38c29beb2de64988282fd2e9#file-myrockertemplate-java-L47) which can take a potentially null value and returns either "" or a default value that was passed along with it.

There could maybe be a both way solution with a maven config?

**Comment by jjlauer** [comment]
Yea, I get bitten by nulls too.  I concur @Optional.ofNullable is a bit
verbose.  Its also not ideal when you just want a replacement string vs.
being type-safe.  I was toying with the idea of an @ifnull method.  If you
could add something to the template language, what would your best proposal
be?

**Comment by awildturtok** [comment]
I actually think that null values not showing are way nicer and more common than when someone does not want them displayed. Or would you change @'s behaviour to not print anything if it is null, but add the @ifnull method to explicitly handle nullable types that need special behaviour?

I really like the language and how fast things get done with it. As you can see I lacked inline conditional behaviour, the ifTrue function is really good for that: Conditionally decorating elements is really easy with it, like adding warning classes to invalid input-fields.

https://github.com/fizzed/rocker/issues/23 is a good idea, but I'd rather see a description language inside the header that would allow this. ContentType is already a member of each template itself, so allow it to be configured.(I remember it not being configurable?) 

Calling templates inside other templates would be a little nicer if I could drop the .template method, but that's really just sugar.

I actually think the language/syntax is in a good state. What it lacks is syntax highlighting, I understand why it's not there I just think this should be the next big point to focus on, even if it were just a cheap sublimetext highlighting, but obviously an IntelliJ plugin would be godsend.

**Comment by jjlauer** [comment]
@awildturtok Latest version v0.13.0 has extensive null handling support.  Should cover all your cases and then some.

**Comment by awildturtok** [comment]
Very nice! This looks way better, than I imagined it.


Am 20.09.2016 um 05:05 schrieb Joe Lauer:
