### ISSUE TITLE
Any API that allow rendering output directly to a stream such as PrintWriter?

### ISSUE THREAD

**Issue by haducloc** [fizzed/rocker#27]
Thank you for awesome engine.  I take a look at all the examples and I didn't see any API that allow rendering output directly to a Stream instead of having a String first?

Proposal API

    templates.stocks
                .template(this.items)
                .render(a_stream_such_as_PrintWriter);

Thank you for your concern!

**Comment by jjlauer** [comment]
Yes, Rocker can do it.  Looks like probably something worthwhile to add to the SYNTAX.md doc if you would be willing to contribute a PR.

The `.render()` method accepts an optional parameter of the RockerOutputFactory to use to create an RockerOutput that your template will be rendered to.  You can implement your own RockerOutput to customize where it renders to or use one of the standard ones.

https://github.com/fizzed/rocker/blob/master/runtime/src/main/java/com/fizzed/rocker/runtime/OutputStreamOutput.java
https://github.com/fizzed/rocker/blob/master/runtime/src/main/java/com/fizzed/rocker/runtime/StringBuilderOutput.java
https://github.com/fizzed/rocker/blob/master/runtime/src/main/java/com/fizzed/rocker/runtime/ArrayOfByteArraysOutput.java

Let's say you wanted to render directly to an OutputStream.  The `OutputStreamOutput` class already implements a wrapper around an outputstream.  If using Java 8 lambdas it would look like this:

```java
templates.stocks.template(this.items)
    .render((contentType, charsetName) -> new OutputStreamOutput(contentType, os, charsetName));
```

The reason you need to supply a factory is that the ContentType and charset is really only known when a render finally occurs.  If you'd like to use an existing PrintWriter, then you would probably want to implement some sort of `PrintWriterOutput` class that implements RockerOutput and then supply it to the render() method.  I'd be excited to have you submit a PR for it.

**Comment by haducloc** [comment]
Thank you!
