### ISSUE TITLE
Gradle support required

### ISSUE THREAD

**Issue by AAverin** [fizzed/rocker#33]
How can I use library in a gradle project?

**Comment by jjlauer** [comment]
Hi @AAverin,

You have a couple options.  The best option would be for you to submit a PR that integrates rocker as a true gradle plugin.  You can base it off the existing maven-plugin for ideas on how to do it.

https://github.com/fizzed/rocker/blob/master/maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java

Another option would be to call https://github.com/fizzed/rocker/blob/master/compiler/src/main/java/com/fizzed/rocker/compiler/JavaGeneratorMain.java from within gradle as an external process of some sort.

**Comment by joselightware** [comment]
buildscript {
  repositories {
  }
  dependencies {
    compile 'com.fizzed:rocker-compiler:0.13.0'
  }
}

task compileRockerTemplates << {
  com.fizzed.rocker.compiler.JavaGeneratorMain.JavaGeneratorMain jgm 
    = new  com.fizzed.rocker.compiler.JavaGeneratorMain.JavaGeneratorMain();
  jgm.getParser().getConfiguration().setTemplateDirectory(new File("src/main/resources"));
  jgm.getParser().getConfiguration().setOutputDirectory(new File("src/main/resources"));
  jgm.getGenerator().getConfiguration().setClassDirectory(new File("src/main/resources"));
  jgm.run();
}

Something like so should work.

**Comment by joselightware** [comment]
Ok my las answer was a bit pseudo coded XD

here is the working build.gradle to use rocker with gradle.

`apply plugin: 'java'
apply plugin: 'application'

sourceCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

mainClassName = "Main"

buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'com.fizzed:rocker-compiler:0.13.0'
  }
}

repositories {
  mavenCentral()
}

dependencies {
  compile 'com.fizzed:rocker-compiler:0.13.0'
  compile 'com.fizzed:rocker-runtime:0.13.0'
  testCompile group: 'junit', name: 'junit', version: '4.10'
}


task compileRockerTemplates << {
    def jgm  = com.fizzed.rocker.compiler.JavaGeneratorMain.newInstance()
    jgm.getParser().getConfiguration().setTemplateDirectory(new File(project.projectDir.toString() +"/src/main/resources"))
    jgm.getParser().getConfiguration().setOutputDirectory(new File(project.projectDir.toString() +"/src/main/java"))
    jgm.getGenerator().getConfiguration().setClassDirectory(new File(project.projectDir.toString()))
    jgm.run()
}

`

Make sure to add templates on "src/main/resources/your/path"
The generated code will be output to "src/main/java/your/path"

![image](https://cloud.githubusercontent.com/assets/2963923/18689112/ce29573a-7f87-11e6-8306-67962bce978f.png)

**Comment by josevimlet** [comment]
Updated the link to gradle example project source since I realised it was wrong.

**Comment by etiennestuder** [comment]
@jjlauer I've published a fully-functional Gradle plugin for creating Rocker templates:
https://github.com/etiennestuder/gradle-rocker-plugin

The plugin comes with a DSL to configure the code generation process, it supports multiple configurations per project, the tasks participates in [incremental builds](https://blog.gradle.org/introducing-incremental-build-support), and when optimization is turned on, the task outputs are cacheable by the [Gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html). More details are described in the [README](https://github.com/etiennestuder/gradle-rocker-plugin/blob/master/README.md) file. The plugin is built with thorough [test coverage](https://github.com/etiennestuder/gradle-rocker-plugin/blob/master/src/test/groovy/nu/studer/gradle/rocker/RockerFuncTest.groovy).

The gradle-rocker-plugin is available on the Gradle Plugin Portal and in JCenter:
https://plugins.gradle.org/plugin/nu.studer.rocker
https://bintray.com/etienne/gradle-plugins/gradle-rocker-plugin

**Comment by jjlauer** [comment]
Latest Rocker version includes a gradle plugin.
