### ISSUE TITLE
@args is messy

### ISSUE THREAD

**Issue by joselightware** [fizzed/rocker#36]
On static templates passing all params on template(arg1, arg2, arg3 ...) can get really really messy when dealing with complex templates since quickly you have to check which param corresponds to a @tag.
A much better approach would be to use a map of strings to assign values to the corresponding tag and pass the map as the template argument.

```
HashMap<String, String> hmap = new HashMap<String, String>();

hmap.put("name", "fizzed");
hmap.put("last", "rocker");
hmap.put("age", "25");

String result = MyTemplate.template(hmap).render().toString();
```

**Comment by jjlauer** [comment]
That's what BindableRockerModel is for.  It lets you create templates
dynamically w/ a map.

The preferred method is preferred for a reason.  If you change the
arguments to a template, you want your compilation process to break, in
order to catch the issues you're refactoring caused.  If you are passing
around a lot of context-specific arguments to your templates, then I highly
suggest you add a parent Model you extend from that has some of that
instead.

-Joe

**Comment by joselightware** [comment]
I've seen on the documentation the BindableRockerModel the only problem is that I cant figure out what path to provide to make it work.

After fixing issue #37 I can make use of static template like so

`TestTemplate.template("Hello World").render().toString();`

the path to the compiled template is

`"src/main/java/com/jo/template/TestTemplate.java"`

the path to the template file is

`"src/main/resources/jo/template/TestTemplate.rocker.html"
`
Now i'm trying to make use of the BindingRockerModel

I've tested the following paths without success

```
Rocker.template("com/jo/template/TestTemplate.rocker.html")
            .bind("world", "Hello Rocker!")
            .render()
            .toString();
  }
```
```
Rocker.template("src/main/resources/com/jo/template/TestTemplate.rocker.html")
            .bind("world", "Hello Rocker!")
            .render()
            .toString();
  }
```
```
Rocker.template("src/main/java/com/jo/template/TestTemplate.rocker.html")
            .bind("world", "Hello Rocker!")
            .render()
            .toString();
  }
```

All with the same exception as result (com.fizzed.rocker.TemplateNotFoundException)
Any idea of what I might be doing wrong.

**Comment by jjlauer** [comment]
The path is the package +template name.

So if your template gets a package of "views" and is named
"index.rocker.html" then you'd say:

Rocker.template("views/index.rocker.html")

**Comment by joselightware** [comment]
Ok, now its working ^_^

**Comment by joselightware** [comment]
Now we have a fully working gradle rocker plugin, the plugin is a mix of many of the thing I use that has nothing to do with rocker so ill strip down the parts that aren't related and PM you the main steps to make a working gradle-rocker-plugin.
