### ISSUE TITLE
Add support for Stream::forEach

### ISSUE THREAD

**Issue by slorion** [fizzed/rocker#40]
Adding support for `Stream::forEach` iteration would a useful feature I think. At this moment, I need to collect the stream into a `List<T>` to be able to use it with `@for` :

``` java
myStream.collect(Collectors.toList());
```

**Comment by bendem** [comment]
See #75 for a workaround using `stream::iterator`.

**Comment by jjlauer** [comment]
Rocker v0.24.0 is out and `Stream.iterator()` now works in the `@for` loop.
