### ISSUE TITLE
Clarify which use case each RockerOutputFactory implementation fits

### ISSUE THREAD

**Issue by bendem** [fizzed/rocker#44]
Reading the docs I naively implemented my first templates using `MailTemplate.template(args).render().toString()`. Reading a bit more between the lines, I realised the default `RockerOutputFactory` is actually `ArrayOfByteArraysOutput` (it's also the one mentioned in the README as the "[optimised output](https://github.com/fizzed/rocker#use-optimized-output)"). Its `toString` method is implemented as
```java
@Override
public String toString() {
    // super inneffecient method to convert to string
    // since byte arrays are guaranteed to be split real chars we need to
    // construct the entire array first before doing final convert to string
    byte[] bytes = toByteArray();
    return new String(bytes, this.charset);
}
```

As the comment says, this is not at all an optimised way to render the template and the documentation should be updated to make this very clear.

I propose to add a section explaining which `RockerOutputFactory` are available and when to use them. The examples relying on `toString` should be updated to use `StringBuilderOutput.FACTORY` (I believe this is the most efficient implementation if you're going to use `toString`).
The "[Use optimized output](https://github.com/fizzed/rocker#use-optimized-output)" should also be updated to precise that it's only optimised if you use `asReadableByteChannel`.

**Comment by jjlauer** [comment]
@bendem Good suggestion on updating the docs.  Added some notes on rendering to Strings in an optimized manner.  Can you check out https://github.com/fizzed/rocker#use-optimized-output and then close this if it answered your question.

**Comment by bendem** [comment]
Much better, should help newcomers use th
