### ISSUE TITLE
"else if" support

### ISSUE THREAD

**Issue by bendem** [fizzed/rocker#47]
I like the idea of being able to write it as `elif`, but at the moment, neither `else if` not `else @if` works.

**Comment by jjlauer** [comment]
Hey,

Appreciate your feedback.  True `else if` support would be good.  Perhaps
someone in the community would be interested to give an implementation a
try.  For now you'll need to nest it yourself like so:

```
@if (false) {
  the-if-block
} else {
  @if (false) {
    the-next-if-block
  } else {
    the-final-else
  }
}
```

**Comment by jjlauer** [comment]
Hey,

Appreciate your feedback.  True `else if` support would be good.  Perhaps
someone in the community would be interested to give an implementation a
try.  For now you'll need to nest it yourself like so:

```java
@if (false) {
  the-if-block
} else {
  @if (false) {
    the-next-if-block
  } else {
    the-final-else
  }
}
```

**Comment by mreuvers** [comment]
This one seems useful to me as well.

I would prefer to just use `@else if` to match with the rest of the syntax (and java).
What is your preference @jjlauer?

I may be able to pick this one up probably somewhere next month, if that's fine feel free to assign to me.

**Comment by jjlauer** [comment]
@mreuvers That would be great if you wanted to take this on.  I'd agree that following java's syntax `} else if (condition) {` would be ideal.

**Comment by mreuvers** [comment]
All right I'll see what I can do. Consider it assigned then.

**Comment by mreuvers** [comment]
Hey @jjlauer 

I had some time earlier, so it's done. Please see the pull request for details.

**Comment by mreuvers** [comment]
Cheers @jjlauer for the maven release. I forgot to mention it earlier. I suppose this bug could be closed now.
