### ISSUE TITLE
support for property expressions

### ISSUE THREAD

**Issue by jknack** [fizzed/rocker#53]
Like `@foo` where foo can be:

- public final? field
- foo() method (no arg, with return type)
- isFoo() method
- getFoo() method

To be clear you can write `@foo` in your template and compiler translate to correct expression.

It add extra work to the rocker compiler but think will be good addition.

**Comment by jjlauer** [comment]
@jknack I get why this could be a useful feature, but compiler checked code is the single most important aspect of why I spent time creating Rocker.  When you start to add features that do not exist in Java, you'll end up inventing strange rules, prioritization, etc.  So I doubt I'd consider adding property support, unless Java itself does.

**Comment by jknack** [comment]
Fair enough, but you already have a couple of no existing expressions like `with` and `enhanced  for-loop`

**Comment by jjlauer** [comment]
Fair enough on your point on the with and special for-loops.

BTW, there's already a concept of "post processing" you could look at.  I
believe you could use that technique to convert something like `@
variable.user.name` to `@variable.getUser().getName()` in your
post-processor -- and it would still compile.
