### ISSUE TITLE
Omit LAST_MODIFIED static header in templates when optimized is true

### ISSUE THREAD

**Issue by mark-vieira** [fizzed/rocker#55]
When using the `optimized` option in the Rocker compiler the hot reloading feature is disabled. Since the `LAST_MODIFIED` field in the compiled templates is only used for this purpose it should be omitted when this option is used. The use case here is that we want to cache these compiled templates and reuse the outputs in conjunction with [Gradle build cache](https://docs.gradle.org/release-candidate/userguide/build_cache.html). Having different outputs for the same inputs breaks this capability. Currently we are manually stripping these fields out.

**Comment by jjlauer** [comment]
Hey Mark,

Sounds reasonable to me.  Would you be interested in helping make that
modification and submitting a PR?

-Joe

**Comment by jjlauer** [comment]
@mark-vieira Took a look at what you suggested and I have a couple questions.  First, the field LAST_MODIFIED doesn't exist -- did you mean MODIFIED_AT ?  Second, that value is the "last modified" value from the source file itself.  I guess my question is -- do you see that value change on your system if you didn't actually the underlying source file?

**Comment by mark-vieira** [comment]
> First, the field LAST_MODIFIED doesn't exist -- did you mean MODIFIED_AT 

Doh, yes :)

> I guess my question is -- do you see that value change on your system if you didn't actually the underlying source file?

Not for local development, but this value changes when doing thinks like fresh checkouts. So two CI builds using the same source will have different compiled output.

**Comment by mark-vieira** [comment]
I've gone ahead and submitted pull request #58 to address this.

**Comment by jjlauer** [comment]
@mark-vieira Excellent work.  Pushed out v0.18.0 to maven central with your changes.

**Comment by etiennestuder** [comment]
Awesome to have this released so quickly!
