### ISSUE TITLE
Add @SuppressWarnings("unused") to generated code

### ISSUE THREAD

**Issue by mnlipp** [fizzed/rocker#59]
I always want my projects to be "warning free" because usually warnings *do* indicate some kind of problem.

When using rocker, I get warnings because of unused imports for simple templates. I can exclude the directory with rocker generated source from the check, of course. But it would also be very simple to fix this without user intervention by adding a `@SuppressWarnings("unused")` to the generated code, e.g.:

```java
/*
 * Auto generated code to render template org/jgrapes/http/demo/httpserver/SubmitResult.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
@SuppressWarnings("unused")
public class SubmitResult extends com.fizzed.rocker.runtime.DefaultRockerModel {
}
```

**Comment by jjlauer** [comment]
Great suggestion.  I know its a 1-liner, but if you wanted to submit a PR,
I'd be happy to merge!  Otherwise, I'll try to add this in at a later date.

**Comment by bendem** [comment]
Would it be worth it to replace the generated comment with the appropriate annotation [`@Generated`](https://docs.oracle.com/javase/8/docs/api/index.html?javax/annotation/Generated.html) while changing that?

**Comment by mnlipp** [comment]
It's a different issue but certainly a good idea. Though I wouldn't replace the comment but add the @Generated. I've found referenced that e.g. checkstyle considers this annotation.

**Comment by jjlauer** [comment]
Both annotations added in v0.20.0
