### ISSUE TITLE
How is it compared to branaway/Japid, also a compiled pure java template engine

### ISSUE THREAD

**Issue by tunggad** [fizzed/rocker#61]
https://github.com/branaway/Japid

**Comment by jjlauer** [comment]
hi @tunggad -- I remember looking at Japid before starting work on Rocker.  I also looked at every other templating library out there before investing time in building this one.  If you take a look at the performance benchmarks, there's a reason Rocker is as fast as it is.  Its not just that it produces compiled templates, its that the way the templates are generated & processed, is pretty novel.  I also worked carefully on the syntax and how the templates can be plugged into different web frameworks.

**Comment by tunggad** [comment]
Thanks you for the explanation!
