### ISSUE TITLE
Readme: RockerRuntime.setReloading(..) does not exist

### ISSUE THREAD

**Issue by mscharhag** [fizzed/rocker#64]
Within the hot reloading section of the readme, the following line of code is shown:

```
RockerRuntime.setReloading(true);
```

However, this does not compile because `RockerRuntime` has no static `setReloading(..)` method.

Maybe it should be `RockerRuntime.getInstance().setReloading(true)`?

**Comment by jjlauer** [comment]
Yes - you are correct that getInstance is required.  Will update the docs.
