### ISSUE TITLE
@?xyz is not null-safe when type of xyz is RockerContent

### ISSUE THREAD

**Issue by etiennestuder** [fizzed/rocker#68]
Having this:
```
@args (RockerContent head)
...
@?head
```
will blow up at runtime if `head` is null.

I tracked it down to the invocation of:

`__internal.renderValue(head, true);`

This method implementation does not look at the `nullSafe` parameter but always calls `render` on `c`, even if `c` is null.
```
com.fizzed.rocker.runtime.DefaultRockerTemplate.Internal#renderValue(com.fizzed.rocker.RockerContent, boolean)
public void renderValue(RockerContent c, boolean nullSafe) throws RenderingException, IOException {
            // delegating rendering this chunk of content to itself
            c.render();
}
```

**Comment by jjlauer** [comment]
@etiennestuder looks like a bug.  Would you be interested in adding a unit test and an associated fix?  Otherwise, it'll be some time until I have extra bandwidth to tackle it.

**Comment by etiennestuder** [comment]
@jjlauer I'll see if I can find some time. Getting the Maven build to run might be my biggest hurdle as a Gradle user ;-)

**Comment by breskeby** [comment]
created PR for this at https://github.com/fizzed/rocker/pull/69

**Comment by etiennestuder** [comment]
Thanks, @breskeby :-)

**Comment by jjlauer** [comment]
v0.22.0 has this fix.  Will be available whenever maven central syncs.
