### ISSUE TITLE
Cannot access external images on template 

### ISSUE THREAD

**Issue by PabloThiele** [fizzed/rocker#81]
Is there any problem to open images on the template? I tried to refer some images (located at same folder of template) using "< img >" tags without luck.

Is there any impediment for this, or anyone can provide me a snippet that have this ?

Thanks in advance.

**Comment by jjlauer** [comment]
@PabloThiele -- I'm not sure what you mean by "open images" in the same folder.  Please copy 'n paste rocker template code you're trying to run so I can understand what you mean.

**Comment by PabloThiele** [comment]
It's a simple logo to be added on my HTML. 
It's huge, but the snippet is : 
`` <div>
        <img src="../images/homer.png">
    </div>
`` 
I think rocker have no problem at all with this, and maybe it's a access issue.

**Comment by jjlauer** [comment]
You don't have any rocker syntax (e.g. `@` chars) in that template snippet.  Rocker would output as text exactly what you wrote.  Your issue sounds like a web server / web framework issue -- not a Rocker issue.  If you need a web framework, I'd suggest you take a look at https://github.com/fizzed/ninja-rocker
